[project]
name = "f1"
version = "0.1.0"
description = ""
authors = [
    {name = "riuler",email = "riulersilverio@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "streamlit (>=1.60.0,<2.0.0)",
    "plotly (>=6.9.0,<7.0.0)",
    "pydantic (>=2.13.4,<3.0.0)"
]

[tool.poetry]
packages = [{include = "f1", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.15.22,<0.16.0)",
    "mkdocs-material (>=9.7.7,<10.0.0)",
    "requests-mock (>=1.12.1,<2.0.0)",
    "taskipy (>=1.14.1,<2.0.0)",
    "pre-commit (>=4.6.1,<5.0.0)"
]

[tool.taskipy.tasks]
lint = "ruff check . --fix && ruff format ."
test = "pytest --cov=src/f1 --cov-report=term-missing"
app = "streamlit run src/f1/interface/app.py"
docs = "mkdocs serve"
docs-build = "mkdocs build"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/f1"]
